# _config.yml
title: "Private Documentation"
description: "My private documents"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Footer settings
footer:
  links:
    enabled: false
