title: "Qxel Documentation"
description: "Official documentation for Qxel"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# (Optional) Just the Docs settings
color_scheme: light
