title: "Private Documentation"
description: "My private documents"
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# (Optional) Just the Docs settings
color_scheme: light
# _config.yml
footer_content: "© 2025 Shameem owns the copyright bro. All rights reserved."
permalink: pretty
