title: "private Documentation"
description: "Official documentation"
remote_theme: mr-izu/elca

plugins:
  - jekyll-remote-theme

# (Optional) Just the Docs settings
color_scheme: light
# _config.yml
footer_content: "© 2025 Shammi. All rights reserved."
permalink: pretty
