# Site title and description
title: "Your Site Title"
title_short: "YST" # Short version for header
description: "Your site description"
keywords: "your,keywords,here"
author: "Qxel"
remote_theme: mr-izu/elca

plugins:
  - jekyll-remote-theme
# Logo (optional)
logo: "https://mr-izu.github.io/logos/qxel/transparent_logo.png" # Path to your logo

# Navigation configuration
navigation:
  - title: "Home"
    url: "/"
  
  - title: "Adnan"
    dropdown:
      - title: "Assignment"
        url: "/adnan/assignment/"
      - title: "Seminar"
        url: "/adnan/seminar/"

  - title: "Jaseel"
    dropdown:
      - title: "Assignment"
        url: "/jaseel/assignment/"
      - title: "Athulya Assignment"
        url: "/jaseel/athulya_assignment/"
      - title: "Navas Assignment"
        url: "/jaseel/navas_assignment/"

  - title: "My Notes"
    dropdown:
      - title: "Aseena Assignment"
        url: "/my/aseena_assignment/"
      - title: "Aseena Seminar"
        url: "/my/aseena_seminar/"
      - title: "Assignment"
        url: "/my/assignment/"
      - title: "Athulya Assignment"
        url: "/my/athulya_assignment/"
      - title: "Seminar"
        url: "/my/seminar/"
      - title: "Suji Assignment"
        url: "/my/suji_assignment/"
      - title: "Suji Seminar"
        url: "/my/suji_seminar/"

  - title: "Noushique"
    dropdown:
      - title: "Assignment"
        url: "/noushique/assignment/"
      - title: "Seminar"
        url: "/noushique/seminar/"
      - title: "Assignment"
        url: "/noushique/assignment/"
      - title: "Seminar"
        url: "/noushique/seminar/"
      - title: "Assignment"
        url: "/noushique/assignment/"
      - title: "Seminar"
        url: "/noushique/seminar/"
      - title: "Assignment"
        url: "/noushique/assignment/"
