# _config.yml
title: "Private Documentation"
description: "My private documents"
theme: jekyll-docs-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional settings
footer:
  copyright: "© 2025 Shameem owns the copyright bro. All rights reserved."
