site_name: Qxel Documentation
site_description: Documentation for Qxel - For Business, Users, and Partners
site_url: https://docs.izumie.me/

repo_name: mr-izu/docs
repo_url: https://github.com/mr-izu/docs

# Use the root directory instead of docs/
docs_dir: .  # This tells MkDocs to use the current directory

# Explicitly ignore any files/directories you don't want included
watch:
  - .  # Watch current directory

nav:
  - Home: index.md
  - Adnan:
    - Assignment: adnan/assignment.md
    - Seminar: adnan/seminar.md
  - Jaseel:
    - Assignment: jaseel/assignment.md
    - Navas Assignment: jaseel/navas_assignment.md
  - My:
    - Assignment: my/assignment.md
    - Athulya Assignment: my/athulya_assignment.md
    - Seminar: my/seminar.md
    - Suji Assignment: my/suji_assignment.md
  - Noushique:
    - Assignment: noushique/assignment.md
    - Seminar: noushique/seminar.md
    - Suji Assignment: noushique/suji_assignment.md
  - Sahad:
    - Assignment: sahad/assignment.md
    - Seminar: sahad/seminar.md
  - Shiyas:
    - Assignment: shiyas/assignment.md
    - Politics Assignment: shiyas/politics_assignment.md
    - Seminar: shiyas/seminar.md
    - Athulya Assignment: shiyas/athulya_assignment.md
    - Suji Seminar: shiyas/suji_seminar.md
  - Sinan:
    - Assignment: sinan/assignment.md
  - Suji Chapter 4: suji_chatper4/index.md

theme:
  name: material
  logo: https://cdn.jsdelivr.net/gh/mr-izu/Images@main/qxel.svg
  favicon: https://cdn.jsdelivr.net/gh/mr-izu/Images@main/qxel.svg
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite

copyright: |
  &copy; 2024 Qxel, Inc. All rights Reserved.
  
extra:
  generator: false
